### ISSUE TITLE
LDAP users cannot apply Language System-Wide

### ISSUE THREAD

**Issue by matjam** [linuxmint/mintlocale#13]
The method grp.getgrall() only gets Unix groups, not groups in NIS or LDAP.

I have users that are in a LDAP directory, and they are added to sudo and adm on login, using /etc/security/group.conf. These users may need to be able to change the system-wide language.

A better approach would be to use a polkit policy, which already works for other things, to determine if they are admin or not. Maybe display the button but require admin rights to apply the change.

**Comment by xenopeek** [comment]
If LDAP users with sudo permissions still can't authorize local system administration tasks with gksu, I'd suggest to look into switching sudo on concerned systems to use LDAP. See upstream [sudoers.ldap](https://www.sudo.ws/man/sudoers.ldap.man.html) manpage for capabilities (found in package sudo-ldap).
