### ISSUE TITLE
mintLocale doesnt support Gtk2 themes

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintlocale#21]
I'm using a Gtk2 theme in Linux Mint Mate 17 (Clearlooks) and the Control Center > Languages dialog doesnt get themed.

**Comment by GLolol** [comment]
It looks like mintLocale is an application written with GTK 3. So, you'll need a matching GTK 3 theme for the app to look nice on your desktop.

Clearlooks-Phenix is a working GTK 3 port of Clearlooks: `apt-get install clearlooks-phenix-theme` on Mint.

**Comment by philipzae** [comment]
Thanks a million.
