### ISSUE TITLE
no support for locale et_EE.utf8

### ISSUE THREAD

**Issue by edmundlaugasson** [linuxmint/mintlocale#24]
the error message is:
Warning: No support for locale: et_EE.utf8

Current workaround:
http://forums.linuxmint.com/viewtopic.php?f=42&t=111527
sudo locale-gen --purge --no-archive
sudo update-initramfs -u

**Comment by xenopeek** [comment]
As noted on the linked topic, this warning you may see with some programs when started from the terminal. If you don't want to see the warning you can use that workaround. It isn't an issue in mintlocale.
