### ISSUE TITLE
Mint doesn't offer to install language-pack-kde-ru k3b-i18n kde-l10n-ru

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/mintlocale#29]
I have installed K3b, but mint doesn't offer me to install localisation packages

**Comment by Yanpas** [comment]
Also Kdenlive is also installe too

**Comment by clefebvre** [comment]
This should help:

https://github.com/linuxmint/mintlocale/commit/a0b54356ed7cdedb47334b0dc93c0a0728ca42fe
https://github.com/linuxmint/mintlocale/commit/b933f7600c3f2df2f42c89252cf606c40b1d3782

Regarding language-pack-kde... should we suggest it when plasma-desktop is installed?

@Yanpas I'll close this issue for now. Feel free to make a PR to add tr::plasma-desktop:language-pack-kde- if you think it's needed.
