### ISSUE TITLE
Language packs are not installed in LMDE2 "Betsy"

### ISSUE THREAD

**Issue by jkirk** [linuxmint/mintlocale#35]
I added a second language (first one is English, US (UTF-8), second one is German, Austria (UTF8).
After that I wanted to install language packs but at least "firefox-l10n-de" and "thunderbird-l10n-de" were not installed.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintlocale/commit/57daae7f3964afe6bc84dbe66fc61f8c7435e5a8
