### ISSUE TITLE
[BUG] "Input method: None" generates .xinputrc with "xim" instead of "none" which produces further bugs

### ISSUE THREAD

**Issue by dqgls** [linuxmint/mintlocale#41]
How to reproduce:
1. delete ~/.xinputrc if there is such a file already, which gets you back to fresh install state
2. open Input method window and keep it open (!) until step 4
    - at this point ~/.xinputrc gets created with `run_im none`
    - while Input method field is blank
3. click on the blank Input method field and select "None"
    - at this point ~/.xinputrc gets overwritten with `run_im xim`
4. close the window, log out and log back in for xim to take effect
5. try slowly scrolling line by line in xed or gnome-terminal: the scrolling is jumpy

From user's standpoint the bug can be solved and prevented from reappearing by replacing `run_im xim` with `run_im none` after closing the Input method window. If ~/.xinputrc already exists selecting "None" does not generate a new one with `run_im xim`. That's why for bug to appear it is necessary that the file does not already exist before opening the window and thus that one does not close the window between steps 2 and 3.

There's probably some problem with the way im-config gets called in that situation, it mixes up "None" with "xim".

**Comment by haarp** [comment]
> try slowly scrolling line by line in xed or gnome-terminal: the scrolling is jumpy

Thanks, I've been trying to figure out for so long where the jumping scrolling was coming from in GTK3 apps!

xim seems to be problematic. Unfortunately it's the only way to have a custom .XCompose be recognized...

**Comment by monsta** [comment]
@clefebvre: I confirm this in 18.1 and 18.2. Another annoying side effect is that "xim" breaks unicode input method of GTK+ (Ctrl-Shift-U, then type character code, then press Enter).

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintlocale/commit/7fdb6a07fda33fc18e845fe1d7ffc8e92bdbf0a1
