### ISSUE TITLE
Fcitx does not work with 18 or 18.1 KDE+Qt 5 apps

### ISSUE THREAD

**Issue by fu-sen** [linuxmint/mintlocale#42]
Linux Mint 18 KDE independently adopted KDE Plasma 5.8 LTS from December 2016.
As a result, since the version of Ubuntu package and Qt are different,
the problem of dependency between fcitx-frontned-qt5 occurs and it is not installed.

I noticed that the Kubuntu team solved this with backports PPA:
https://launchpad.net/~kubuntu-ppa/+archive/ubuntu/backports/+packages?field.name_filter=fcitx&field.status_filter=published&field.series_filter=xenial

I solved the problem with this package:
![screenshot_20170202_232015](https://cloud.githubusercontent.com/assets/5434159/22553304/91650b78-e99f-11e6-9393-25952ad85172.jpg)

If this can be applied to Linux Mint KDE, Asian users will be delighted.
I troubled the place to report and reported here.

**Comment by xenopeek** [comment]
I don't think this is an issue in the mintlocale program, right? As Linux Mint KDE uses the Kubuntu backports PPA I assume this is solved as you describe.
