### ISSUE TITLE
show/install missing language packages via command line

### ISSUE THREAD

**Issue by SethosII** [linuxmint/mintlocale#43]
Ubuntu offers `check-language-support` to display missing language packages on the command line. The command also checks for application specific packages like `chromium-browser-l10n`. The problem is that Linux Mint doesn't offer this tool.

However it's possible to show installed languages and install missing packages with `mintlocale` but it only offers a GUI (at least I couldn't find documentation on command line usage) and I would like to automate it.

Is there a way to do this via the command line?

**Comment by brkeh** [comment]
Why don't you install `language-selector-common` which includes `check-language-support`? Works for me on Mint 17.3 Mate.

**Comment by SethosII** [comment]
@brkeh Thanks for the hint. I thought that `mintlocale` might provide something similar as it internally does the same? And in general I would like to control the program via the command line.

**Comment by brkeh** [comment]
I'm not familiar with mintlocale. I'd have to investigate. I don't have time right now.

**Comment by xenopeek** [comment]
Thanks for contributing to mintlocale. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
