### ISSUE TITLE
_usr_lib_linuxmint_mintlocale_install_remove.py.0.crash

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/mintlocale#50]
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintlocale/install_remove.py", line 282, in button_remove_clicked
    f.write("%s\tdeinstall\n" % pkg.name)
  File "/usr/lib/python3.5/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'

**Comment by xenopeek** [comment]
I can't reproduce it on Linux Mint 18.3 when adding language packs or adding a language in mintlocale.

If the issue happens again, please test against the latest mintlocale version, go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be mintstick. We'd need more detailed information on steps to reproduce it.
