### ISSUE TITLE
mate.desktop

### ISSUE THREAD

**Issue by SavSanta** [linuxmint/mintlocale#54]
i think my most recent upgrade changed the Language and  Region settings to mate.desktop

This permeated thru to everything launched in my mate session including:
uxterm: uxterm tried unsuccessfully to use locale mate.UTF-8 by setting $LANG to "mate.UTF-8
mate terminal:  ~ $ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=mate.desktop
LANGUAGE=
LC_CTYPE="mate.desktop"
LC_NUMERIC="mate.desktop"
LC_TIME="mate.desktop"
LC_COLLATE="mate.desktop"
LC_MONETARY="mate.desktop"
LC_MESSAGES="mate.desktop"
LC_PAPER="mate.desktop"
LC_NAME="mate.desktop"
LC_ADDRESS="mate.desktop"
LC_TELEPHONE="mate.desktop"
LC_MEASUREMENT="mate.desktop"
LC_IDENTIFICATION="mate.desktop"
LC_ALL=

Changelog says version is
mintlocale (1.3.1) rosa; urgency=medium

  * Fixed a few issues in iminfo
  * Tuned IM info for Korean
  * Partially tuned IM info for Chinese (need more info from a Chinese user...)
  * IM: Added lists for Thai and Vietnamese

**Comment by clefebvre** [comment]
Can you show the content of:

~/.pam_environment
~/.dmrc
/etc/default/locale

Also when you run mintlocale from the terminal, what does it output in the terminal?

**Comment by SavSanta** [comment]
I fixed it by changing the settings thru the GUI in the "Languages Settings"(aka mintlocale) a long while back.

However for edificiation here is what it is now.

```
santa@home ~ $ cat ~/.pam_environment 
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
PAPERSIZE=letter
santa@home ~ $ cat ~/.dmrc 
[Desktop]
Session=mate
Language=en_US.UTF-8

santa@home ~ $ cat /etc/default/locale 
LANG="en_US.UTF-8"
santa@home ~ $ 

```

Before in

**Comment by trendfischer** [comment]
I could confirm this bug. Something is setting the LANG and LC_* environments to "mate.desktop". It is easy to fix, but how can this happen? 

I did not installed or updated any packages. A recursive grep for "mate.desktop" in /etc/* or ~/.config/ found no hit.

Is there any other GUI application, which could manipulate the locale settings beside mintlocale? I could not find any hint for this bug in this repository here.

**Comment by trendfischer** [comment]
Seems to be an issue with the MDM display manager or something else setting MDM_LANG to "mate.desktop", and MDM changes the locale settings so it is probably right to have this issue closed here.
