### ISSUE TITLE
Leave mint-common parts as optional

### ISSUE THREAD

**Issue by SamBurgos** [linuxmint/mintlocale#55]
This morning I updated the mintlocale package for Arch Linux users, and after a couple of tests of why the application was not working, I found that it now depends on package mintcommon, which is not available outside of Mint, and if can't make it depend on it, while checking mintcommon I see that it depends on many APT things (which, again, are not available outside of Mint). Is it possible for you to leave mintcommon and all the related pieces as optional?

The commit would be [this one](https://github.com/linuxmint/mintlocale/commit/2747d9eb778a6639e32f079ae40103e7c962fe5f), I guess that users of Fedora (my apologies for the spam @leigh123linux ) and other distros might have this problem as well so I hope this can help to either revert it or put it as optional. If this dependency is forced as of this version onwards, then please let us know so maybe we can find another alternative in this case

My apologies if it sounds rude (which I don't intend) and I hope to hear an answer about it so I can check what to do (I am the co-maintainer of mintlocale on Arch Linux). Kind regards

**Comment by leigh123linux** [comment]
@SamBurgos Thank you for addressing this issue, I have used your pr for the latest fedora build

https://src.fedoraproject.org/cgit/rpms/mintlocale.git/commit/?id=db4e60ae630730edee88deca70870163e2fce56c
