### ISSUE TITLE
LMDE 3 Calamers install fails with necryption on NVMe drive

### ISSUE THREAD

**Issue by edover2019** [linuxmint/mintlocale#68]
I tried to install LMDE 3 on an NVMe drive using the encryption option in Calamares installer, but I get errors. It seems the drive encryption on NVMe is buggy, or not supported.

I was able to reproduce the same error when attempting to install LMDE 3 on a virtualized NVMe drive. LMDE 3 installs fine on an SSD drive using encryption.

Debian 9 installer does not have this issue.

![LMDE 3 Install Error](https://user-images.githubusercontent.com/53305481/61879048-be97ba00-aee1-11e9-9923-174ab1d7a170.png)

**Comment by clefebvre** [comment]
Not related to mintlocale.
