### ISSUE TITLE
Incorrect label ?

### ISSUE THREAD

**Issue by vegam57** [linuxmint/mintlocale#77]
![スクリーンショット 2021-09-05 06-28-07](https://user-images.githubusercontent.com/78515193/132108772-7efceae7-048e-42e8-9b7d-cf7e08d3f13a.png)

**Comment by clefebvre** [comment]
@vegam57 it looks correct to me. Only one of these sentences is shown to the user (for a particular language). The combination depends on that language (basically it depends on whether or not we use fcitx).
