### ISSUE TITLE
German language cannot be fully installed due to conflicting packages

### ISSUE THREAD

**Issue by uliw-tech** [linuxmint/mintlocale#83]
There are conflicting packages in the list of packages for the German language.

E.g. package "hunspell-de-at-frami" conflicts "hunspell-de-at".

As soon as one conflicting package is installed, the respective other conflicting package is removed (see screenshot).

![Screenshot from 2024-08-27 18-19-03](https://github.com/user-attachments/assets/4b3dc351-11d8-406d-9b04-b80c1c6e3174)

**Comment by trombonekale** [comment]
Same problem here with package "hunspell-de-de" and "hunspell-de-de-frami".
![sprache](https://github.com/user-attachments/assets/6417e1ce-7f1e-4b83-84bb-3c6a2964b763)

**Comment by bttrx** [comment]
Same on Mint 22 MATE
